FROM python:3.8.18-slim-bookworm
WORKDIR /opt/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY src/scripts ./src/scripts
COPY src/regex ./src/regex
COPY iris-lfs-storage/model-best ./src/scripts/model-best
COPY iris-lfs-storage/model-gpt ./src/scripts/model-gpt
COPY iris-lfs-storage/model-extended ./src/scripts/model-extended
CMD ["python3", "src/scripts/nlp_server.py"]